# Generated by Django 5.2.7 on 2026-02-04 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('music', 'Music'), ('book', 'Book'), ('article', 'Article')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='uploads/previews/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('digital_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='files.digitalfile')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('pages', models.PositiveIntegerField()),
                ('digital_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='files.digitalfile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('digital_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_detail', to='files.digitalfile')),
            ],
        ),
        migrations.CreateModel(
            name='MusicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('digital_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_detail', to='files.digitalfile')),
            ],
        ),
    ]
